name = "edgetunnel"
main = "_worker.js"
compatibility_date = "2025-11-04"
workers_dev = true
keep_vars = true

[[kv_namespaces]]
binding = "KV"
id = "273381e4a0ff47358f5043313cdf4217"

[[routes]]
pattern = "a.yiyiqi.ccwu.cc"
custom_domain = true
